module.exports = async function (self) {
	self.setVariableDefinitions([
		{ variableId: 'deviceType', name: 'Device Type' },
		{ variableId: 'hostName', name: 'Host Name' },
		{ variableId: 'serialNumber', name: 'Serial Number' },
		{ variableId: 'firmwareVersion', name: 'Firmware Version' },
		{ variableId: 'firmwareSecVersion', name: 'Secondary Firmware Version' },
		{ variableId: 'fpgaVersion', name: 'FPGA Version' },
		{ variableId: 'hardwareRevsion', name: 'Hardware Revsion' },
		{ variableId: 'macAddress', name: 'MAC Address' },
		{ variableId: 'ipAddress', name: 'IP Address' },
		{ variableId: 'netMask', name: 'Subnet Mask' },
		{ variableId: 'gateway', name: 'Gateway' },
		{ variableId: 'dhcp', name: 'DHCP' },
		{ variableId: 'channelCount', name: 'Channel Count' },
		{ variableId: 'linkGroup', name: 'Link Group' },
		{ variableId: 'clockSource', name: 'Clock Source' },
		{ variableId: 'adatMirror', name: 'ADAT Mirror' },
		{ variableId: 'inputOffset', name: 'Input Channel Offset' },
		{ variableId: 'blinkMode', name: 'Blink Mode' },
		{ variableId: 'clientUDP', name: 'UDP Clients' },
		{ variableId: 'clientTCP', name: 'TCP Clients' },
		{ variableId: 'sampleRate', name: 'Sample Rate' },
		{ variableId: 'switchHeadroom', name: 'Switch Headroom' },
		{ variableId: 'master', name: 'Master' },
		{ variableId: 'heartBeat', name: 'HeartBeat' },
		{ variableId: 'lwip', name: 'LWIP' },
		{ variableId: 'dsp', name: 'DSP' },
		{ variableId: 'tcpip', name: 'TCPIP' },
		{ variableId: 'macRX', name: 'Mac RX' },
		{ variableId: 'macTX', name: 'Mac TX' },
		{ variableId: 'rtosHeapFree', name: 'RTOS Heap Free' },
		{ variableId: 'mallocHeadFree', name: 'Malloc Heap Free' },
		{ variableId: 'sceneCount', name: 'Scene Count' },
		{ variableId: 'sceneActive', name: 'Active Scene' },
		{ variableId: 'sceneActiveIndex', name: 'Active Scene Index' },
		{ variableId: 'sceneActiveChanged', name: 'Active Scene Changed' },
		{ variableId: 'channelName1', name: 'Channel 1 Name' },
		{ variableId: 'channelName2', name: 'Channel 2 Name' },
	])
}
